# Generated by Django 2.1.1 on 2018-10-18 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181017_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bomsheet',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatherItem', to='blog.ItemSheet'),
        ),
        migrations.AddField(
            model_name='bomsheet',
            name='son',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonItem', to='blog.ItemSheet'),
        ),
    ]
