# Generated by Django 2.1.1 on 2018-10-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181018_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsheet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='typesheet',
            name='id',
        ),
        migrations.AlterField(
            model_name='tagsheet',
            name='tag',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='typesheet',
            name='type',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
