# Generated by Django 2.1.1 on 2018-10-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181018_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesheet',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='articlesheet',
            name='type',
        ),
    ]
