# Generated by Django 2.1.1 on 2018-10-18 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181018_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesheet',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.TagSheet'),
        ),
        migrations.AddField(
            model_name='articlesheet',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.TypeSheet'),
        ),
    ]
